{% set name = "spirv-headers" %}
{% set version = "1.3.246.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/sdk-{{ version }}.tar.gz
    sha256: 71668e18ef7b318b06f8c466f46abad965b2646eaa322594cd015c2ac87133e6

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make    # [unix]
    - ninja   # [win]
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/include/spirv/1.2/spirv.h             # [unix]
    - if not exist %LIBRARY_INC%\\spirv\\1.2\\spirv.h exit 1  # [win]

about:
  home: https://github.com/KhronosGroup/SPIRV-Headers
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Machine-readable files for the SPIR-V Registry

extra:
  recipe-maintainers:
    - isuruf
